sudo: true
services:
- docker
install:
- sudo apt-get update && sudo apt-get install -y jq
script:
- ./local-build.sh
- ./build-repositories.sh
# Build all artifacts
- http_proxy= https_proxy= ./build-artifact.sh apache-aurora-${TRAVIS_BRANCH}.tar.gz ${TRAVIS_BRANCH}

